apiVersion: v1
kind: Service
metadata:
  name: {{ include "tensor-fusion.fullname" . }}
  namespace: {{ include "tensor-fusion.namespace" . }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    {{- include "tensor-fusion.controller.selectorLabels" . | nindent 6 }}